namespace RelatedSetCommon
{
    [default_interface]
    runtimeclass PluginWrapper
    {
        PluginWrapper();
        Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Controls.UserControl> Plugins();
    }
}
