namespace RelatedSetHostAppNativeHelper
{
    [default_interface]
    runtimeclass NativeHelper
    {
        NativeHelper();
        String LoadDll(String path);
        String AddPlugins(Windows.UI.Xaml.Controls.StackPanel panel);
    }
}
