namespace RelatedSetHostAppNativeHelper
{
    runtimeclass PluginWrapper
    {
        PluginWrapper();
        Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Controls.UserControl> Plugins();
    }
}
